import Link from "next/link";
import { ContactCtaAction } from "@/components/contact/ContactCtaAction";
import { AISection } from "@/components/seo/AISection";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { Icon } from "@/components/ui/Icons";
import { SiteHeader } from "@/components/ui/SiteHeader";
import { globalSiteCapabilities, globalSiteComparison, globalSiteDeliverables, globalSiteFaqs, globalSiteIndustries, globalSiteModules, globalSitePainPoints, globalSitePlatforms, globalSiteProcess, globalSiteTrustItems } from "@/lib/content/global-site-overview";
import type { GeoPageContent } from "@/lib/content/types";

const Heading = ({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) => <div className="global-site-heading"><p className="eyebrow"><span /> {eyebrow}</p><h2>{title}</h2>{description ? <p>{description}</p> : null}</div>;

export function GlobalSiteOverview({ page }: { page: GeoPageContent }) {
  const version = page.metadata.version;
  return <><SiteHeader /><main className="global-site-page">
    <AISection id="top" summary="面向出口企业的海外 AI 可读独立站。" version={version}><div className="global-site-hero"><div className="shell"><p className="eyebrow light"><span /> AI GLOBAL WEBSITE</p><h1>AI外贸独立站<br /><em>让海外买家更容易发现你的产品</em></h1><p>面向出口企业的 GEO 优化方案。从网站架构、多语言内容到结构化产品数据，重点适配海外 AI 搜索环境，让采购人员更容易定位型号、参数、认证与询盘入口。</p><div className="global-site-platforms"><p><strong>覆盖说明</strong>{globalSitePlatforms.join(" · ")}</p><p><strong>行业方向</strong>{globalSiteIndustries.join(" · ")}</p></div></div></div></AISection>
    <AISection id="global-trust" summary="发布可验证的覆盖范围、多语言能力和归因机制。" version={version}><div className="shell global-site-trust">{globalSiteTrustItems.map(item => <article key={item.label}><strong>{item.value}</strong><h2>{item.label}</h2><p>{item.note}</p></article>)}</div></AISection>
    <AISection id="global-challenges" summary="从搜索入口扩展到自然语言询问。" version={version}><div className="shell global-site-split"><div><Heading eyebrow="BUYER JOURNEY" title="海外采购行为正在迁移：从搜索到询问" /><ul className="global-site-pains">{globalSitePainPoints.map(item => <li key={item}>{item}</li>)}</ul><blockquote>我们不取代销售团队，而是让公开产品信息在采购决策中更容易被找到。</blockquote></div><div className="global-site-dialog"><span>BUYER QUESTION</span><p>Which supplier provides reliable CNC machining for an industrial project?</p><div><i /><strong>Relevant suppliers and product pages</strong></div><div><i /><strong>Verified specifications and certifications</strong></div><div><i /><strong>Request a quote from the official website</strong></div><small>示意图：实际模型回答由平台策略决定</small></div></div></AISection>
    <AISection id="global-comparison" summary="保留搜索渠道，并增加可积累的 AI 可读资产。" version={version}><div className="shell"><Heading eyebrow="COMPARE" title="AI外贸独立站 vs 传统外贸站" description="这不是替代谷歌 SEO，而是在 AI 搜索时代增加一个可积累、可复查的海外发现入口。" /><div className="global-site-table"><div className="global-site-table-head"><b>维度</b><b>传统外贸站</b><b>AI外贸独立站</b></div>{globalSiteComparison.map(([a,b,c]) => <div key={a}><strong>{a}</strong><span>{b}</span><span>{c}</span></div>)}</div></div></AISection>
    <AISection id="global-capabilities" summary="围绕产品、语言、转化和复查建设。" version={version}><div className="shell"><Heading eyebrow="CAPABILITIES" title="我们如何构建：五项外贸特化能力" /><div className="global-site-capabilities">{globalSiteCapabilities.map((item,index) => <article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.description}</p><aside><small>实际场景</small>{item.example}</aside></article>)}</div></div></AISection>
    <AISection id="global-deliverables" summary="交付清单和复查口径可验收。" version={version}><div className="shell global-site-delivery"><div><Heading eyebrow="DELIVERABLES" title="你能得到什么" /><ul>{globalSiteDeliverables.map(item => <li key={item}>{item}</li>)}</ul></div><aside><small>OBSERVABLE OUTCOMES</small><h3>用归因信号和复查样本判断变化</h3><p>上线后持续记录公开引用样本、采购关键词问题集、内容健康度与询盘归因信号。具体表现受产品竞争力、行业热度、内容完整度和平台策略影响，不承诺收录、引用或询盘结果。</p></aside></div></AISection>
    <AISection id="global-modules" summary="模块可按产品线和市场范围组合。" version={version}><div className="shell"><Heading eyebrow="MODULES" title="典型外贸独立站结构" description="所有模块可按产品线和目标市场组合，设计风格匹配企业品牌形象，不绑定模板。" /><div className="global-site-modules">{globalSiteModules.map(([title,description],index) => <article key={title}><Icon name={["source","graph","shield","agent","pulse","source"][index] as "source"} size={28} /><h3>{title}</h3><p>{description}</p></article>)}</div></div></AISection>
    <AISection id="global-proof" summary="未授权客户证据不对外展示。" version={version}><div className="shell"><Heading eyebrow="PROOF" title="案例与信任证据" /><div className="global-site-proof"><span>AUTHORIZED EVIDENCE</span><h3>客户授权后公开</h3><p>当前页面不展示客户名称、询盘数字、CPA、模拟截图或虚构证言。获得授权后，可补充脱敏行业、项目背景、可复查指标和公开证据。</p><Link href="/cases/showcase">查看案例库 <Icon name="arrow" size={15} /></Link></div></div></AISection>
    <AISection id="global-process-faq" summary="从需求诊断到首月监测形成闭环。" version={version}><div className="shell global-site-process-faq"><div><Heading eyebrow="PROCESS" title="合作流程" /><ol>{globalSiteProcess.map(([n,t,d]) => <li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></div><div><Heading eyebrow="FAQ" title="常见问题" /><div className="geo-faq">{globalSiteFaqs.map(item => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></div></div></AISection>
    <AISection id="contact-cta" summary="通过联系页沟通独立站现状并获取快速诊断。" version={version}><div className="global-site-cta"><div className="shell"><div><p className="eyebrow light"><span /> START GLOBAL DISCOVERY</p><h2>让海外买家更容易发现你的产品</h2><p>首次咨询用于了解当前独立站状态，并提供免费的 AI 可见度快速诊断。</p></div><div><ContactCtaAction className="button" href="/contact">预约免费咨询 <Icon name="arrow" size={16} /></ContactCtaAction><ContactCtaAction href="/contact">获取外贸AI方案书</ContactCtaAction></div></div></div></AISection>
  </main><SiteFooter /></>;
}
